### ISSUE TITLE
Arguments Error

### ISSUE THREAD

**Issue by iamajvillalobos** [JuanitoFatas/comer_de_tapas#1]
```
Force fetching. Getting latest Ruby Tapas...
Fetching episodes...
Authorizing...
/Users/ajvillalobos/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/http-1.0.4/lib/http/chainable.rb:195:in `auth': wrong number of arguments (given 2, expected 1) (ArgumentError)
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/comer_de_tapas-0.2.1/lib/comer_de_tapas/client.rb:149:in `get_feed_with_basic_auth'
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/comer_de_tapas-0.2.1/lib/comer_de_tapas/client.rb:37:in `fetch_episodes!'
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/comer_de_tapas-0.2.1/lib/comer_de_tapas/client.rb:21:in `download'
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/comer_de_tapas-0.2.1/lib/comer_de_tapas/cli.rb:27:in `download'
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/comer_de_tapas-0.2.1/bin/comer_de_tapas:7:in `<top (required)>'
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/bin/comer_de_tapas:22:in `load'
    from /Users/ajvillalobos/.rbenv/versions/2.3.0/bin/comer_de_tapas:22:in `<main>'
```

I have my credentials setup already. Any help?

**Comment by JuanitoFatas** [comment]
I am sorry, this project is obsoleted. I don't use it anymore for a long time. Please try other alternatives from [Ruby Tapas FAQ](http://www.rubytapas.com/faq). Thank you.
